name: Deploy to Oracle Cloud

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copyfiles to server
        run: |
          rsync -avz --exclude '.git*' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/projects/code-climb/src

      - name: Deploy with Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~/projects/code-climb/src
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
          EOF
    
